version: '3'

services:
  project-db:
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - project-database

  project-service:
    image: project-service
    container_name: project-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8082:8082
    volumes:
      - /data/project-service
    networks:
      - project-database
      - network

networks:
  project-database:
    driver: bridge
  network:
    driver: bridge
